name: Image Replacement

on:
  push:
    branches:
      - main
    paths:
      - project_pbo.jpg  # Specify the path to the image you want to monitor

jobs:
  replace_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace Image
        run: |
          # Replace the existing image with the new one
          cp project_pbo.jpg project_pbo_backup.jpg  # Optional: Backup the old image
          cp path/to/new/image.jpg project_pbo.jpg  # Update this path to the new image location
          
          # Configure Git
          git config --local user.email "jordanjosia929@gmail.com"  # Set your email
          git config --local user.name "JustJorr"           # Set your name
          
          # Commit and push the changes
          git add project_pbo.jpg
          git commit -m "Replace project_pbo.jpg with new upload"
          git push
